### ISSUE TITLE
Q: Feature requests

### ISSUE THREAD

**Issue by Eric89GXL** [andreyzhd/VideoMEG#2]
I can edit and update if this seems like the right place to put these things.

1. The shutter/gain/color settings are not persistent in the GUI. The camera seems to maintain them, but closing and reopening VideoRecStation, the settings are not saved. These could be added to the config file and read on program load.

2. Dummy video mode for testing.

3. Persistent video window locations and sizes.

**Comment by Eric89GXL** [comment]
Updated the list of things I will probably take care of, because they would be really nice to have at our end. We only run a 1280x960 resolution, so having the window size and location persist across open/closing of the program would be nice. And if I'm going to work on that, I want to do it on my dev computer, which is not hooked up to any cameras, so I need a way of running using a "dummy" mode.

What is your workflow for building / testing?

**Comment by Eric89GXL** [comment]
Never mind, I see the `.pro` which is probably enough for me. However, it would be good to know which version of Qt you are using so that if I compile something the version stays the same...

**Comment by andreyzhd** [comment]
I'm using Qt 5.2.1 right now. Probably, any Qt 5.x.x would do.
As for the workflow, I do not have a very elaborate formal procedure. If it compiles and runs ("runs" means passing a quick informal test: switching the cameras on/off, recording a few tens of seconds of data, etc.), I make a commit.

**Comment by Eric89GXL** [comment]
Closing in favor of PR #4
