### ISSUE TITLE
BUG: SyncDaemon doesn't send triggers

### ISSUE THREAD

**Issue by Eric89GXL** [andreyzhd/VideoMEG#5]
I'm setting up the new computer and can't get SyncDaemon to send triggers out the parallel port. I have used two different parallel port cards and neither works. One of the two cards I even used successfully in a different computer, and it works with SyncDaemon there. However, I know it isn't a hardware problem, since I can use the "parallel" package in Python to toggle the parallel port output bit states, which I know gets access through /dev/parport0. Any ideas for how to fix this? I'll try tweaking the SyncDaemon C code to see if I can get it to work, hopefully sometime this week.

BTW do you know offhand the command for building SyncDaemon? I'm assuming it's a simple `gcc` one-liner, but I thought I should check. Either way, I can add it to a `Makefile` so that the next time it needs to be built one can just do `make` to get it to build.

**Comment by andreyzhd** [comment]
Guessing the correct port address has always been tricky. So far I managed to get away with either 12304 (0x3010), or 888 (0x378), or some number from the output of 'cat /proc/ioports | grep parport'. Accessing the port through /dev/parport0 will probably make the software more portable. I'll take a look at it.

The command for building SyncDaemon is 'gcc main.c -o SyncDaemon'

**Comment by Eric89GXL** [comment]
I used all the port addresses listed in that `grep parport` line and they didn't work, which is strange. I'm not sure how to query Linux to know which set of addresses `/dev/parport0` is using, which would be nice to know...

In any case, it is possible that using `/dev/parport0` (or allowing the user to pass the dev address) might work better, not sure. I think at a minimum it will require blacklisting / `rmmod`'ing the `lp` kernel module, and maybe also adding the user to the `lp` group. I think I had to do these things to get Python's `parallel` module to get access to `/dev/parport0`.

**Comment by Eric89GXL** [comment]
Looking at this:

http://as6edriver.sourceforge.net/Parallel-Port-Programming-HOWTO/accessing.html

```
One thing they suggest to do for "direct IO" mode (which the current iteration uses) is this:

Before a port may be accessed directly, the driver must claim access to the address space.
Normally one uses the iopl() call.

#include <sys/io.h>

int result = iopl(3); /* Returns 0 on success */

This call requires root access and will return -1 if it is not available.
```
I don't see this done in the SyncDaemon code. I might try adding it to see if it fixes the problem if I get a chance.

**Comment by Eric89GXL** [comment]
Although `ioperm`, which is suggested later, I think is used... hmm.

**Comment by andreyzhd** [comment]
I think, ioperm should be enough. In recent kernel versions it can claim any address in the 0 -- 0xffff range, not only up to 0x3ff.
I've googled some examples of the code that uses the "/dev/parport0" format, but doing it properly will require more time than I have right now.

**Comment by Eric89GXL** [comment]
Okay, I'll see if I can get it working in the meantime.

**Comment by Eric89GXL** [comment]
One option is triaging which mode to use (sys io vs /dev/parport0) based on the argument? In other words, this would use the old mode:
```
SyncDaemon 12304 255
```
Whereas this would use the `/dev/parport0` mode?
```
SyncDaemon /dev/parport0 255
```
It doesn't seem like it will be too difficult to triage, since the failure to convert `/dev/parport0` into an integer is easy to detect. This has the advantage that either system could be used, but the disadvantage that we'd have to code paths to support. WDYT?

**Comment by Eric89GXL** [comment]
If only having one mode makes sense and you don't mind it being `/dev/parport0`, I can also work on just changing the code over.

**Comment by andreyzhd** [comment]
I think both ways (a separate `/dev/parport` version of SyncDaemon, and a triage approach) are OK. I cannot see how one is clearly superior to the other. Probably, having a separate version is the way to start, since it's a bit easier. Anyway, I'd like to keep the portnumber-based option available (either as a separate file or thorugh triage) even if the `/dev/parport` option works. Also, one needs to check the performance of the `/dev/parport`-based approach. In theory, it can be slower, though in practice I think the difference is negligible. But this needs to be tested.

**Comment by Eric89GXL** [comment]
This is now working. I switched parallel port cards, maybe that fixed it. Or maybe I was just doing something dumb... in any case, we're good!
